name: Build DirectXShaderCompiler

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -C ./cmake/caches/PredefinedParams.cmake -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=Release 

      - name: Build
        run: |
          ninja
