name: Build DirectXShaderCompiler

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake . \
            -C ./cmake/caches/PredefinedParams.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build .
