name: Build DirectXShaderCompiler

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -C cmake/caches/PredefinedParams.cmake
      
      - name: Build
        run: cmake --build build --config Release
