name: Build DirectXShaderCompiler

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build \
            -G "Visual Studio 17 2022" \
            -T ClangCL \
            -A x64 \
            -C cmake/caches/PredefinedParams.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang-cl \
            -DCMAKE_CXX_COMPILER=clang-cl \
            -DHLSL_BUILD_DXILCONV=OFF \
            -DENABLE_SPIRV_CODEGEN=OFF \
            -DLLVM_ENABLE_LTO=ON \
            -DHLSL_OFFICIAL_BUILD=ON \
            -DCMAKE_C_FLAGS="/arch:AVX2" \
            -DCMAKE_CXX_FLAGS="/arch:AVX2"
      
      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/Release/bin/
