name: Build DirectXShaderCompiler

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          .\utils\hct\hctstart.cmd . .\build
          .\utils\hct\hctbuild.cmd -x64 -Release -show-cmake-log
